import { Guitar } from './types/data';

export const mockOffer: Guitar = {
  id: 2,
  name: 'CURT Z300',
  vendorCode: 'TK129049',
  type: 'electric',
  description: 'Эргономичность гитары и качество сборки являются, пожалуй, её главными преимуществами. Идеальное расположение в руках музыканта дополняется прочностью конструкции из клёна.',
  previewImg: 'img/guitar-8.jpg',
  stringCount: 7,
  rating: 3.5,
  price: 29500,
  comments: [
    {
      id: 'H4uxZEGZ1MfLUSnSzdhHr',
      userName: 'Никита',
      advantage: 'Хорошо. Очень хорошо.',
      disadvantage: 'Покрытие.',
      comment: 'Это моя первая гитара. Все понравилось. Сделано качественно.',
      rating: 4,
      createAt: '2021-12-08T17:06:57.863Z',
      guitarId: 2,
    },
    {
      id: 't2IcxvlHvi5wqnd3TfsE1',
      userName: 'Ольга',
      advantage: 'Недорогая, за такую цену звук отличный.',
      disadvantage: 'Не комплект.',
      comment: 'Это моя первая гитара. Все понравилось. Сделано качественно.',
      rating: 2,
      createAt: '2021-11-11T17:06:57.863Z',
      guitarId: 2,
    },
    {
      id: 'FBg3pOlF-oSfLvhvW98-Q',
      userName: 'Максим',
      advantage: 'Цена=качество.',
      disadvantage: 'Плохо. Очень плохо.',
      comment: 'Гитара пришла, за такие деньги неплохо, но гриф чуть кривой, изза этого звук в 5-3 струне звенит, для новичков сойдёт.',
      rating: 4,
      createAt: '2021-12-11T17:06:57.863Z',
      guitarId: 2,
    },
    {
      id: '6RkYZ8Tga8o835UnFUio6',
      userName: 'Даша',
      advantage: 'Нет.',
      disadvantage: 'Не рекомендую!',
      comment: 'В целом для домашнего использования и дворовых песен в самый раз!',
      rating: 2,
      createAt: '2021-12-06T17:06:57.863Z',
      guitarId: 2,
    },
    {
      id: 'BtkjSdrqJ1oEi8j8vXDlh',
      userName: 'Саша',
      advantage: 'Хорошо. Очень хорошо.',
      disadvantage: 'Нет.',
      comment: 'Это моя первая гитара. Все понравилось. Сделано качественно.',
      rating: 3,
      createAt: '2021-11-15T17:06:57.863Z',
      guitarId: 2,
    },
    {
      id: 'MUuwJEg-56YaEV5BSFMmH',
      userName: 'Даша',
      advantage: 'Легкая в плане веса, изготовлена на много аккуратнее чем советские гитары.',
      disadvantage: 'Плохо. Очень плохо.',
      comment: 'Неплохо, но дорого.',
      rating: 4,
      createAt: '2021-11-11T17:06:57.863Z',
      guitarId: 2,
    },
    {
      'id': 'RJpfu0NgI9e4WY4wVHJnn',
      'userName': 'Максим',
      'advantage': 'Цена.',
      'disadvantage': 'Плохие стоковые струны, гриф.',
      'comment': 'Когда в наличии будет в чёрном цвете?',
      'rating': 2,
      'createAt': '2021-11-13T17:06:57.863Z',
      'guitarId': 2,
    },
    {
      id: 'bPNhwBSpU6keW7NwxNKUI',
      userName: 'Саша',
      advantage: 'Цена.',
      disadvantage: 'Не рекомендую!',
      comment: 'Хорошая гитара для начинающих, сделана качественно. Лучше за эти деньги не найти.',
      rating: 2,
      createAt: '2021-12-13T17:06:57.863Z',
      guitarId: 2,
    },
    {
      id: 'RW5pum7KuWfsNwa89fHOu',
      userName: 'Артём',
      advantage: 'Звук, внешний вид.',
      disadvantage: 'Быстро приходит в негодность покрытие краской.',
      comment: 'Подарила сыну на первое сентября прошлого года. Пришла целой. Для начала гитара сойдёт.',
      rating: 1,
      createAt: '2021-12-04T17:06:57.863Z',
      guitarId: 2,
    },
  ],
};
